services:
  mi-xiaoai:
    image: mi-xiaoai:latest
    container_name: mi-xiaoai
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    env_file:
      - ./config/.env
    volumes:
      - ./config/.migpt.js:/app/.migpt.js:ro
      - ./state/.mi.json:/app/.mi.json
      - ./state/.bot.json:/app/.bot.json
      - ./state/app.db:/app/prisma/app.db

networks:
  default:
    name: mi-xiaoai
    ipam:
      config:
        - subnet: 172.31.255.0/24
